import { test } from 'node:test';
import assert from 'node:assert/strict';
import { codes } from './database-fixture.mjs';
const base=process.env.TEST_APP_URL||'http://127.0.0.1:3101';
const requestOrigin=process.env.TEST_REQUEST_ORIGIN||base;
async function api(path,{body,cookie,origin=requestOrigin,method}={}){
 return fetch(base+path,{method:method||(body===undefined?'GET':'POST'),headers:{Origin:origin,...(body===undefined?{}:{'Content-Type':'application/json'}),...(cookie?{Cookie:cookie}:{})},body:body===undefined?undefined:JSON.stringify(body)});
}
test('HTTP: closed invitations, privacy, responses and cross-group attacks',async()=>{
 const anonymous=await api('/api/rsvp');assert.equal(anonymous.status,401);assert.match(anonymous.headers.get('cache-control'),/no-store/);
 const home=await (await fetch(base)).text();assert.ok(!home.includes('Buffet Napoleão'));assert.ok(!home.includes('R. Rio Branco, 58'));assert.ok(!home.includes('Troca de alianças'));assert.ok(!home.includes('Estacionamento ao lado'));assert.ok(!home.includes('Valet na porta'));assert.ok(!home.includes(codes.silva));assert.ok(!home.includes('test-service-role'));
 assert.equal((await api('/api/invitations/access',{body:{code:'INVALID'}})).status,404);
 assert.equal((await api('/api/invitations/access',{body:{code:codes.inactive}})).status,403);
 assert.equal((await api('/api/invitations/access',{body:{code:codes.silva},origin:'https://outside.example'})).status,403);
 const upperCaseOpen=await api('/api/invitations/access',{body:{code:'6D88EECF1CDEA14190ABA9B50B63DBA3'}});
 assert.equal(upperCaseOpen.status,200);
 const open=await api('/api/invitations/access',{body:{code:'6d88eecf1cdea14190aba9b50b63dba3'}});
 assert.equal(open.status,200);
 const expectedSlug='demo-familia-silva-'+codes.silva.toLowerCase();
 assert.equal((await upperCaseOpen.json()).slug,expectedSlug);assert.equal((await open.clone().json()).slug,expectedSlug);
 const cookie=open.headers.get('set-cookie').split(';')[0];
 assert.match(open.headers.get('set-cookie'),/HttpOnly/i);
 assert.match(open.headers.get('set-cookie'),/SameSite=strict/i);
 const read=await api('/api/rsvp',{cookie});assert.equal(read.status,200);const invitation=await read.json();
 assert.equal(invitation.guests.length,3);assert.equal(invitation.event.venue,'Buffet Napoleão — Espaço Praça');assert.match(invitation.event.address,/R\. Rio Branco, 58/);assert.equal(invitation.event.reception_time,'13h');assert.equal(invitation.event.ceremony_time,'16h');
 assert.ok(!JSON.stringify(invitation).includes(codes.oliveira));assert.ok(!JSON.stringify(invitation).includes(codes.silva));
 const response={guests:invitation.guests.map((g,index)=>({id:g.id,status:'confirmed',phone:g.type==='adult'?`1199999000${index+1}`:null})),dietary_restrictions:'Pedro: sem lactose',notes:'Obrigado pelo convite'};
 let saved=await api('/api/rsvp',{cookie,body:response});assert.equal(saved.status,200);assert.equal((await saved.json()).updated,false);
 response.guests[0].phone='11999991111';response.guests[2].status='declined';response.notes='Atualizado';
 saved=await api('/api/rsvp',{cookie,body:response});assert.equal(saved.status,200);assert.equal((await saved.json()).updated,true);
 const reopen=await api('/api/invitations/access',{body:{slug:'demo-familia-silva-'+codes.silva.toLowerCase()}});
 assert.equal(reopen.status,200);
 const persisted=await (await api('/api/rsvp',{cookie:reopen.headers.get('set-cookie').split(';')[0]})).json();
 assert.equal(persisted.rsvp.notes,'Atualizado');assert.equal(persisted.rsvp.dietary_restrictions,'Pedro: sem lactose');assert.equal(persisted.guests[0].phone,'11999991111');assert.equal(persisted.guests[1].phone,'11999990002');assert.equal(persisted.guests[2].phone,null);assert.equal(persisted.guests[2].attendance_status,'declined');
 const otherOpen=await api('/api/invitations/access',{body:{code:codes.oliveira}});
 const otherCookie=otherOpen.headers.get('set-cookie').split(';')[0];
 const other=await (await api('/api/rsvp',{cookie:otherCookie})).json();
 assert.equal(other.guests.length,2);
 assert.equal((await api('/api/rsvp',{cookie,body:{...response,invitation_group_id:other.id}})).status,400);
 assert.equal((await api('/api/rsvp',{cookie,body:{...response,guests:[{id:other.guests[0].id,status:'confirmed',phone:'11999992222'},...response.guests.slice(1)]}})).status,400);
 assert.equal((await api('/api/rsvp',{cookie:cookie+'x'})).status,401);
 assert.equal((await api('/api/rsvp',{body:response})).status,401);
 const untouched=await (await api('/api/rsvp',{cookie:otherCookie})).json();assert.equal(untouched.rsvp,null);
 assert.equal((await api('/api/rsvp',{cookie,body:{...response,notes:'x'.repeat(2001)}})).status,400);
 assert.equal((await api('/api/rsvp',{cookie,body:{...response,notes:'x'.repeat(17000)}})).status,413);
 let throttled=false;for(let i=0;i<15;i++){if((await api('/api/invitations/access',{body:{code:'INVALID'}})).status===429){throttled=true;break;}}assert.equal(throttled,true);
});
