import Image from 'next/image';
import { DreamPhoto } from '@/components/dream-photo';
import { WeddingLogo } from '@/components/wedding-logo';
import { Navigation } from '@/components/navigation';
import { Countdown } from '@/components/countdown';
import { Photo } from '@/components/photo';
import { ArrowDownIcon, ArrowUpRightIcon } from '@/components/icons';
import story from '@/content/story.json';

const chapters = [
  { date: '23.01.2023', name: 'O encontro', text: 'Dois atrasos. Dois grupos diferentes. Uma mesma trilha. Na Pedra do Elefante, uma conversa no meio do caminho se tornou o primeiro passo da nossa história.' },
  { date: '19.02.2023', name: 'O começo', text: 'Começamos oficialmente a caminhar juntos. Entre descobertas, risadas, manias e sonhos, o eu foi dando espaço para o nós.' },
  { date: '23.12.2024', name: 'O pedido', text: 'Um sim, e tantos planos. Começamos a imaginar as cores, a casa e o dia em que reuniríamos as pessoas que amamos.' },
  { date: '18.12.2025', name: 'Quando os planos mudaram', text: 'Um grave acidente de moto mudou o ritmo da nossa caminhada. O casamento precisou esperar. Entre cuidados e recuperação, aprendemos que amar também é ajudar o outro a levantar — e escolher ficar.' },
  { date: '21.11.2026', name: 'O nosso sim', text: 'Diante de Deus, da nossa família e dos nossos amigos, daremos mais um passo. O casamento será o começo de uma nova parte.' },
];

export default function Home() {
  return <><a className="skip-link" href="#conteudo">Pular para o conteúdo</a><Navigation /><main id="conteudo">
    <section id="inicio" className="hero section-shell">
      <div className="hero-copy"><p className="eyebrow"><span className="short-line" /> UMA VIDA. UMA CAMINHADA.</p><h1 className="hero-brand"><WeddingLogo size="hero" /></h1><p className="hero-intro">A nossa história começou em uma trilha.<br />O próximo passo, queremos dar com você.</p><div className="hero-actions"><a className="button primary" href="#presenca">Confirmar presença <ArrowUpRightIcon /></a><a className="text-link" href="#presentes">Lista de presentes <ArrowUpRightIcon /></a></div></div>
      <div className="hero-image-wrap"><span className="image-kicker">DESDE O PRIMEIRO ENCONTRO</span><Photo className="hero-photo" caption="O nosso lugar é juntos" /><span className="image-date">23.01.2023 · O INÍCIO DA NOSSA HISTÓRIA</span></div>
      <div className="hero-bottom"><a href="#historia" className="scroll-link"><ArrowDownIcon /> Conheça nossa caminhada</a><span className="handwritten">caminhando juntos</span></div>
    </section>
    <section className="countdown-band" aria-labelledby="count-title"><div><p className="eyebrow">CADA DIA, MAIS PERTO</p><h2 id="count-title">Até o nosso sim.</h2></div><Countdown /></section>
    <section id="historia" className="story-section section-shell"><Image className="story-ornament" src="/images/papelaria/Ornamento_Ramos_Coracao.png" alt="" aria-hidden="true" width={260} height={104} /><div className="section-heading"><p className="eyebrow">01 / NOSSA HISTÓRIA</p><h2>Algumas histórias começam<br />com um plano.<br /><em>A nossa, com uma caminhada.</em></h2><p>Hoje acreditamos que Deus já conhecia cada passo,<br className="desktop-break" /> antes mesmo de entendermos o que estava começando.</p></div><div className="story-layout"><div className="story-photos"><Photo caption="A beleza de dividir os dias" number="02" /><p className="photo-quote">O eu começou<br />a dar espaço<br /><em>para o nós.</em></p><Photo caption="Um passo de cada vez" number="03" className="secondary-photo" /></div><div className="timeline"><svg className="journey-line" viewBox="0 0 50 1000" preserveAspectRatio="none" aria-hidden="true"><path d="M24 0 C-4 160 57 180 26 330 S2 530 25 650 S47 820 24 1000" /></svg>{chapters.map((chapter, index) => <article className="chapter" key={chapter.date}><span className="chapter-dot" aria-hidden="true">{String(index + 1).padStart(2, '0')}</span><time dateTime={chapter.date.split('.').reverse().join('-')}>{chapter.date}</time><h3>{chapter.name}</h3><p>{chapter.text}</p></article>)}</div></div><details className="full-story"><summary>Ler nossa história completa <span aria-hidden="true">+</span></summary><div className="full-story-content story-text">{story.map((paragraph, index) => <p key={index} className={paragraph.length < 65 ? "story-beat" : undefined}>{paragraph}</p>)}</div></details></section>
    <section className="choice"><DreamPhoto className="choice-background" objectPosition="50% 46%" src="/images/casal/pe-22.jpg" alt="" aria-hidden="true" fill sizes="100vw" /><div className="choice-frame"><p className="eyebrow">ENTRE TODOS OS CAMINHOS</p><h2>“Eu escolhi você.”</h2><p>Não apenas nos dias fáceis.<br />Também nos dias em que continuar foi uma escolha.</p><span className="handwritten">e continuo escolhendo.</span></div></section>
    <section id="pessoas" className="people-section section-shell"><div className="section-heading"><p className="eyebrow">02 / NINGUÉM CAMINHA SOZINHO</p><h2>Pessoas que<br /><em>caminham conosco.</em></h2><p>Presenças que tornam a nossa história ainda mais bonita.</p></div><div className="people-groups">{[{ title: 'Damas de Honra', people: ['Keila', 'Renata', 'Nathally', 'Mary', 'Jessica'] }, { title: 'Amigos do Noivo', people: ['Vinicius', 'Ronan', 'Danilo', 'Vini', 'Junior'] }].map(group => <div className="people-group" key={group.title}><h3>{group.title}</h3><ul>{group.people.map(name => <li key={name}><span className="person-initial" aria-hidden="true">{name[0]}</span><span>{name}</span></li>)}</ul></div>)}</div></section>
    <section id="dia" className="event-section section-shell"><div className="event-heading"><p className="eyebrow">03 / O GRANDE DIA</p><h2>Um novo capítulo.<br /><em>Com você por perto.</em></h2><p>Cerimônia e recepção no mesmo local.<br />Um dia inteiro para celebrar o amor e estar junto.</p><a className="text-link" href="#presenca">Ver informações do meu convite <ArrowUpRightIcon /></a></div><div className="event-card"><Image className="event-floral" src="/images/papelaria/Arranjo_Floral_Intenso_Transparente.png" alt="" aria-hidden="true" width={160} height={160} /><p className="eyebrow">SÁBADO</p><p className="event-date">21<span>novembro · 2026</span></p><div className="event-schedule"><div><span>13:00</span><p>Recepção</p></div><div><span>16:00</span><p>Troca das alianças</p></div></div><h3>Buffet Napoleão</h3><p>São Bernardo do Campo/SP</p><p className="arrival-note">Pedimos que chegue com 15 minutos de antecedência.</p><p className="privacy-note">O endereço e as orientações de chegada ficarão disponíveis na área privada do seu convite.</p></div></section>
    <section id="presenca" className="rsvp-section section-shell"><p className="eyebrow">04 / ESPERAMOS VOCÊ</p><h2>Vamos dar esse passo<br /><em>juntos?</em></h2><p>Sua presença faz parte da nossa história.</p><div className="availability-note"><span className="status-dot" aria-hidden="true" /><div><strong>Confirmações em breve</strong><p>A confirmação será feita com o código individual do seu convite, somente para as pessoas convidadas.</p></div></div></section>
    <section id="presentes" className="gifts-intro section-shell"><div><p className="eyebrow">05 / PARA A VIDA QUE VEM</p><h2>Um carinho para<br /><em>o nosso novo começo.</em></h2></div><div><p>O maior presente é ter você conosco. Para quem quiser fazer parte dos nossos próximos sonhos, estamos preparando uma lista com carinho.</p><span className="coming-soon">Lista de presentes em breve</span></div></section>
    <div className="closing-photo"><DreamPhoto src="/images/casal/pe-26.jpg" alt="Erik lendo uma carta enquanto Paula sorri emocionada, sentados juntos junto à janela." width={6240} height={4160} objectPosition="50% 50%" sizes="(max-width: 600px) 88vw, 900px" /></div><footer className="footer"><p className="eyebrow">A TRILHA FOI APENAS O PRIMEIRO PASSO.</p><blockquote>“Não importa quantas vezes a vida mude os nossos planos;<br /> nós não queremos mudar o plano de ficar juntos.”</blockquote><Image className="footer-landscape" src="/images/papelaria/rodape_site.png" alt="Montanhas em aquarela, um caminho entre árvores e os dizeres: Paula & Erik. Juntos, sempre mais longe." width={1536} height={707} unoptimized /><p className="footer-verse">Eclesiastes 4:12</p><a href="#inicio" className="back-top">Voltar ao início ↑</a></footer>
  </main></>;
}


